# Generated by Django 4.0.3 on 2022-05-02 21:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_comment_create_date_remove_post_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 2, 21, 19, 50, 437388, tzinfo=utc)),
        ),
    ]
